name: WIF test
on: workflow_dispatch

permissions:
  contents: read
  id-token: write   # indispensable : autorise GitHub à émettre le jeton OIDC

jobs:
  dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.WIF_PROVIDER }}
          service_account: ${{ vars.DEPLOYER_SA }}
      - uses: google-github-actions/setup-gcloud@v2
      - run: |
          gcloud auth list
          gcloud storage ls --project=${{ vars.GCP_PROJECT_ID }}

  prod:
    needs: dev
    runs-on: ubuntu-latest
    environment: prod          # approbation manuelle exigée
    steps:
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.WIF_PROVIDER }}
          service_account: ${{ vars.DEPLOYER_SA }}
      - uses: google-github-actions/setup-gcloud@v2
      - run: |
          gcloud auth list
          gcloud storage ls --project=${{ vars.GCP_PROJECT_ID }}
